apiVersion: apps/v1
kind: Deployment
metadata:
  name: shapes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shapes
  template:
    metadata:
      labels:
        app: shapes
    spec:
      containers:
      - name: shapes-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: shapes-colors