apiVersion: v1
kind: Service
metadata:
  name: shapes-service
spec:
  selector:
    app: shapes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # You can use NodePort to expose the service for testing
